package io.github.xbeeant.easy.core.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 * cache
 */
public class Cache extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * id
     */
    private Long id;

    /**
     * 
     * cache type
     */
    private String type;

    /**
     * 
     * cache owner id
     */
    private String owner;

    /**
     * 
     * expire time
     */
    private Date expireAt;

    /**
     * 
     * cache value
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cache
     *
     * @mbg.generated Sat Apr 10 21:49:30 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field id
     * @return id id
     */
    public Long getId() {
        return id;
    }

    /**
     * set filed id
     * @param id the value for id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field cache type
     * @return type cache type
     */
    public String getType() {
        return type;
    }

    /**
     * set filed cache type
     * @param type the value for cache type
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * get field cache owner id
     * @return owner cache owner id
     */
    public String getOwner() {
        return owner;
    }

    /**
     * set filed cache owner id
     * @param owner the value for cache owner id
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * get field expire time
     * @return expireAt expire time
     */
    public Date getExpireAt() {
        return expireAt;
    }

    /**
     * set filed expire time
     * @param expireAt the value for expire time
     */
    public void setExpireAt(Date expireAt) {
        this.expireAt = expireAt;
    }

    /**
     * get field cache value
     * @return value cache value
     */
    public String getValue() {
        return value;
    }

    /**
     * set filed cache value
     * @param value the value for cache value
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }
}