package io.github.xbeeant.easy.core.model;

import io.github.xbeeant.core.BaseModelObject;

import java.io.Serializable;

/**
 * 区域
 */
public class Geographic extends BaseModelObject<Long> implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 父ID
     */
    private Long pid;

    /**
     * 区域编码
     */
    private String adcode;

    /**
     * 城市编码
     */
    private String citycode;

    /**
     * 行政区名称
     */
    private String name;

    /**
     * 区域中心点
     */
    private String center;

    /**
     * 行政区划级别
     * <p>
     * country:国家
     * province:省份（直辖市会在province和city显示）
     * city:市（直辖市会在province和city显示）
     * district:区县
     * street:街道
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geographic
     *
     * @mbg.generated Sun Jan 10 19:12:39 CST 2021
     */
    private static final long serialVersionUID = 1L;

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }


    public String getName() {
        return this.name;
    }

    /**
     * 获取 主键
     *
     * @return id 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置 主键
     *
     * @param id 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 父ID
     *
     * @return pid 父ID
     */
    public Long getPid() {
        return this.pid;
    }

    /**
     * 设置 父ID
     *
     * @param pid 父ID
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * 获取 区域编码
     *
     * @return adcode 区域编码
     */
    public String getAdcode() {
        return this.adcode;
    }

    /**
     * 设置 区域编码
     *
     * @param adcode 区域编码
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode;
    }

    public String getCitycode() {
        return this.citycode;
    }

    /**
     * 设置 城市编码
     *
     * @param citycode 城市编码
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * comment
     * @param name the value of name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取 区域中心点
     *
     * @return center 区域中心点
     */
    public String getCenter() {
        return this.center;
    }

    /**
     * 设置 区域中心点
     *
     * @param center 区域中心点
     */
    public void setCenter(String center) {
        this.center = center;
    }


    /**
     * 获取 行政区划级别      <p>      country:国家      province:省份（直辖市会在province和city显示）      city:市（直辖市会在province和city显示）      district:区县      street:街道
     *
     * @return level 行政区划级别      <p>      country:国家      province:省份（直辖市会在province和city显示）      city:市（直辖市会在province和city显示）      district:区县      street:街道
     */
    public String getLevel() {
        return this.level;
    }

    /**
     * 设置 level.
     *
     * <p>通过 getLevel() 获取 level</p>
     *
     * @param level level
     */
    public void setLevel(String level) {
        this.level = level;
    }
}