package io.github.xbeeant.easy.core.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 * 密钥管理
 */
public class SecurityKey extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * ID
     */
    private Long id;

    /**
     *
     * security_key.expire_at
     */
    private Date expireAt;

    /**
     * 
     * 密钥对
     */
    private String keyPair;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table security_key
     *
     * @mbg.generated Sat Apr 10 21:38:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field ID
     * @return id ID
     */
    public Long getId() {
        return id;
    }

    /**
     * set filed ID
     * @param id the value for ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field security_key.expire_at
     * @return expireAt security_key.expire_at
     */
    public Date getExpireAt() {
        return expireAt;
    }

    /**
    security_key.expire_at
     *
     * @param expireAt the value for security_key.expire_at
     */
    public void setExpireAt(Date expireAt) {
        this.expireAt = expireAt;
    }

    /**
     * get field 密钥对
     * @return keyPair 密钥对
     */
    public String getKeyPair() {
        return keyPair;
    }

    /**
     * set filed 密钥对
     * @param keyPair the value for 密钥对
     */
    public void setKeyPair(String keyPair) {
        this.keyPair = keyPair == null ? null : keyPair.trim();
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }
}