package io.github.xbeeant.easy.core.model;

import io.github.xbeeant.core.BaseModelObject;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * 账号
 */
public class User extends BaseModelObject<Long> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Jan 11 09:44:00 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 登录账号名
     */
    private String account;
    /**
     * 头像
     */
    private String avatar;
    /**
     * 城市
     */
    private String city;
    /**
     * 国家
     */
    private String country;
    /**
     * 区县
     */
    private String district;
    /**
     * 邮件
     */
    private String email;
    /**
     * 分组ID
     */
    private Long groupId;
    /**
     * 用户ID
     */
    @ApiModelProperty()
    private Long id;
    /**
     * 是否禁用， 0 正常 1 已禁用
     */
    private Integer invalid;
    /**
     * 手机号
     */
    private String mobile;
    /**
     * 昵称：
     */
    private String nickname;
    /**
     * 密码
     */
    private String password;
    /**
     * 区域编码
     */
    private String prefix;
    /**
     * 个人简介
     */
    private String profile;
    /**
     * 省份
     */
    private String province;
    /**
     * 街道
     */
    private String street;
    /**
     * 头衔
     */
    private String title;

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    /**
     * get field 登录账号名
     *
     * @return account 登录账号名
     */
    public String getAccount() {
        return account;
    }

    /**
     * set filed 登录账号名
     *
     * @param account the value for 登录账号名
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * get field 头像
     *
     * @return avatar 头像
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * set filed 头像
     *
     * @param avatar the value for 头像
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * get field 城市
     *
     * @return city 城市
     */
    public String getCity() {
        return city;
    }

    /**
     * set filed 城市
     *
     * @param city the value for 城市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * get field 国家
     *
     * @return country 国家
     */
    public String getCountry() {
        return country;
    }

    /**
     * set filed 国家
     *
     * @param country the value for 国家
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * get field 区县
     *
     * @return district 区县
     */
    public String getDistrict() {
        return district;
    }

    /**
     * set filed 区县
     *
     * @param district the value for 区县
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * get field 邮件
     *
     * @return email 邮件
     */
    public String getEmail() {
        return email;
    }

    /**
     * set filed 邮件
     *
     * @param email the value for 邮件
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * get field 分组ID
     *
     * @return groupId 分组ID
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * set filed 分组ID
     *
     * @param groupId the value for 分组ID
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * get field 用户ID
     *
     * @return id 用户ID
     */
    public Long getId() {
        return id;
    }

    /**
     * set filed 用户ID
     *
     * @param id the value for 用户ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field 是否禁用， 0 正常 1 已禁用
     *
     * @return invalid 是否禁用， 0 正常 1 已禁用
     */
    public Integer getInvalid() {
        return invalid;
    }

    /**
     * set filed 是否禁用， 0 正常 1 已禁用
     *
     * @param invalid the value for 是否禁用， 0 正常 1 已禁用
     */
    public void setInvalid(Integer invalid) {
        this.invalid = invalid;
    }

    /**
     * get field 手机号
     *
     * @return mobile 手机号
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * set filed 手机号
     *
     * @param mobile the value for 手机号
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * get field 昵称
     *
     * @return nickname 昵称
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * set filed 昵称
     *
     * @param nickname the value for 昵称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * get field 密码
     *
     * @return password 密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * set filed 密码
     *
     * @param password the value for 密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * get field 区域编码
     *
     * @return prefix 区域编码
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * set filed 区域编码
     *
     * @param prefix the value for 区域编码
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * get field 个人简介
     *
     * @return profile 个人简介
     */
    public String getProfile() {
        return profile;
    }

    /**
     * set filed 个人简介
     *
     * @param profile the value for 个人简介
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

    /**
     * get field 省份
     *
     * @return province 省份
     */
    public String getProvince() {
        return province;
    }

    /**
     * set filed 省份
     *
     * @param province the value for 省份
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * get field 街道
     *
     * @return street 街道
     */
    public String getStreet() {
        return street;
    }

    /**
     * set filed 街道
     *
     * @param street the value for 街道
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * get field 头衔
     *
     * @return title 头衔
     */
    public String getTitle() {
        return title;
    }

    /**
     * set filed 头衔
     *
     * @param title the value for 头衔
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}