package io.github.xbeeant.easy.core.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * user
 */
public class User extends BaseModelObject<Long> {

    /**
     * 用户ID
     */
    private Long id;

    /**
     * 登录账号名
     */
    private String account;

    /**
     * 头像
     */
    private String avatar;

    /**
     * 国家ID
     */
    private Long countryId;

    /**
     * 城市ID
     */
    private Long cityId;

    /**
     * 省份ID
     */
    private Long provinceId;

    /**
     * 区县ID
     */
    private Long districtId;

    /**
     * 街道
     */
    private String street;

    /**
     * 邮箱
     */
    private String email;

    /**
     * 区域编码
     */
    private String prefix;

    /**
     * 手机号
     */
    private String mobile;

    /**
     * 是否禁用， 0 正常 1 已禁用
     */
    private byte[] invalid;

    /**
     * 昵称
     */
    private String nickname;

    /**
     * 密码
     */
    private String password;

    /**
     * 个人简介
     */
    private String profile;

    /**
     * 头衔
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Thu Mar 18 23:05:51 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 用户ID
     * @return id 用户ID
     */
    public Long getId() {
        return id;
    }

    /**
     * set filed 用户ID
     * @param id the value for 用户ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field 登录账号名
     * @return account 登录账号名
     */
    public String getAccount() {
        return account;
    }

    /**
     * set filed 登录账号名
     * @param account the value for 登录账号名
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * get field 头像
     * @return avatar 头像
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * set filed 头像
     * @param avatar the value for 头像
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * get field 国家ID
     * @return countryId 国家ID
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * set filed 国家ID
     * @param countryId the value for 国家ID
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * get field 城市ID
     * @return cityId 城市ID
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * set filed 城市ID
     * @param cityId the value for 城市ID
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * get field 省份ID
     * @return provinceId 省份ID
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * set filed 省份ID
     * @param provinceId the value for 省份ID
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * get field 区县ID
     * @return districtId 区县ID
     */
    public Long getDistrictId() {
        return districtId;
    }

    /**
     * set filed 区县ID
     * @param districtId the value for 区县ID
     */
    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }

    /**
     * get field 街道
     * @return street 街道
     */
    public String getStreet() {
        return street;
    }

    /**
     * set filed 街道
     * @param street the value for 街道
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * get field 邮箱
     * @return email 邮箱
     */
    public String getEmail() {
        return email;
    }

    /**
     * set filed 邮箱
     * @param email the value for 邮箱
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * get field 区域编码
     * @return prefix 区域编码
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * set filed 区域编码
     * @param prefix the value for 区域编码
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * get field 手机号
     * @return mobile 手机号
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * set filed 手机号
     * @param mobile the value for 手机号
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * get field 是否禁用， 0 正常 1 已禁用
     * @return invalid 是否禁用， 0 正常 1 已禁用
     */
    public byte[] getInvalid() {
        return invalid;
    }

    /**
     * set filed 是否禁用， 0 正常 1 已禁用
     * @param invalid the value for 是否禁用， 0 正常 1 已禁用
     */
    public void setInvalid(byte[] invalid) {
        this.invalid = invalid;
    }

    /**
     * get field 昵称
     * @return nickname 昵称
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * set filed 昵称
     * @param nickname the value for 昵称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * get field 密码
     * @return password 密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * set filed 密码
     * @param password the value for 密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * get field 个人简介
     * @return profile 个人简介
     */
    public String getProfile() {
        return profile;
    }

    /**
     * set filed 个人简介
     * @param profile the value for 个人简介
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

    /**
     * get field 头衔
     * @return title 头衔
     */
    public String getTitle() {
        return title;
    }

    /**
     * set filed 头衔
     * @param title the value for 头衔
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public Long valueOfKey() {
        return id;
    }

    public void assignKeyValue(Long value) {
        this.id = value;
    }
}
