server:
  servlet:
    context-path: /account
    session:
      cookie:
        path: /
        name: esession
  port: 8080
  tomcat:
    max-http-form-post-size: 20


spring:
  datasource:
    druid:
      db-type: mysql
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${SQL_HOST:localhost}:3306/easy_core?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
    username: ${SQL_USR:root}
    password: ${SQL_PWD:root}
#  redis:
#    host: localhost
#    port: 6379
#    username: ""
#    password: ""
#    lettuce:
#      shutdown-timeout: 100
  jackson:
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，
    # SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
    # 不为空的属性才会序列化,具体属性可看JsonInclude.Include
    default-property-inclusion: NON_NULL
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      write_numbers_as_strings: true
  session:
    store-type: jdbc
    timeout: 1800
    redis:
      namespace: easy:session
    jdbc:
      initialize-schema: embedded
      # every 3 minutes
      cleanup-cron: 0 */3 * * * *
      table-name: session
logging:
  level:
    com.xstudio: DEBUG

app:
  permit:
    - "/api/login"
    - "/api/user/register"
    - "/api/authroity/**"
    - "/"

