package io.github.xbeeant.easy.file.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 * easy_files
 */
public class File extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * 文件ID
     */
    private Long id;

    /**
     * 
     * 创建时间
     */
    private Date creatAt;

    /**
     * 
     * 创建人ID
     */
    private Long creatBy;

    /**
     * 
     * 文件名
     */
    private String name;

    /**
     * 
     * 文件大小
     */
    private Integer size;

    /**
     * 
     * 文件MD5
     */
    private String md5;

    /**
     * 
     * 文件SHA256
     */
    private String sha256;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table easy_files
     *
     * @mbg.generated Sat Jan 30 22:21:52 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 文件ID
     * @return id 文件ID
     */
    public Long getId() {
        return id;
    }

    /**
     * set filed 文件ID
     * @param id the value for 文件ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field 创建时间
     * @return creatAt 创建时间
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * set filed 创建时间
     * @param creatAt the value for 创建时间
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }

    /**
     * get field 创建人ID
     * @return creatBy 创建人ID
     */
    public Long getCreatBy() {
        return creatBy;
    }

    /**
     * set filed 创建人ID
     * @param creatBy the value for 创建人ID
     */
    public void setCreatBy(Long creatBy) {
        this.creatBy = creatBy;
    }

    /**
     * get field 文件名
     * @return name 文件名
     */
    public String getName() {
        return name;
    }

    /**
     * set filed 文件名
     * @param name the value for 文件名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field 文件大小
     * @return size 文件大小
     */
    public Integer getSize() {
        return size;
    }

    /**
     * set filed 文件大小
     * @param size the value for 文件大小
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * get field 文件MD5
     * @return md5 文件MD5
     */
    public String getMd5() {
        return md5;
    }

    /**
     * set filed 文件MD5
     * @param md5 the value for 文件MD5
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * get field 文件SHA256
     * @return sha256 文件SHA256
     */
    public String getSha256() {
        return sha256;
    }

    /**
     * set filed 文件SHA256
     * @param sha256 the value for 文件SHA256
     */
    public void setSha256(String sha256) {
        this.sha256 = sha256 == null ? null : sha256.trim();
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }
}